ARG EVOLUTION_BASE_IMAGE=evoapicloud/evolution-api:v2.3.7
FROM ${EVOLUTION_BASE_IMAGE}

LABEL org.opencontainers.image.source="https://github.com/sergiomentorian/wahub"
LABEL io.mentorian.whatsapp-provider="evolution"
